name: Homepage

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn

      # cleanup
      - run: rm -rf docs
      # build libraries
      - run: yarn build
      # homepage
      - run: yarn build
        working-directory: ./packages/website
      - run: cp -r ./packages/website/dist ./docs
      - name: Github Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
